name: "ðŸš€ CD"
on:
  push:
    branches: [ main ]
    paths:
      - "version"
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: "â¬ Checkout Git Repository"
        uses: actions/checkout@v4

      - name: "ðŸ§® Get Release Version"
        shell: bash
        run: |
          version=$(cat version)
          version_minor=${version%.*}
          version_major=${version%%.*}

          echo "VERSION=$version" >> $GITHUB_ENV
          echo "VERSION_MINOR=$version_minor" >> $GITHUB_ENV
          echo "VERSION_MAJOR=$version_major" >> $GITHUB_ENV

      - name: "ðŸ·ï¸ Create Git Tags"
        shell: bash
        run: |
          git tag --force ${{ env.VERSION }}
          git tag --force ${{ env.VERSION_MINOR }}
          git tag --force ${{ env.VERSION_MAJOR }}
          git push --tags --force

      - name: "ðŸš€ Create GitHub Release"
        uses: softprops/action-gh-release@v2.0.4
        with:
          tag_name: ${{ env.VERSION }}
          name: ${{ env.VERSION }}
          generate_release_notes: true

  image-tags:
    needs: [release]
    uses: maandr/github-actions/.github/workflows/cd-generate-image-tags.yaml@v3
    with:
      image: ghcr.io/${{ github.repository }}

  build-matrix:
    runs-on: ubuntu-latest
    outputs:
      available_images: ${{ steps.build-matrix.outputs.available_images }}
    steps:
      - name: "â¬ Checkout Git Repository"
        uses: actions/checkout@v4

      - name: "ðŸ¤– Detect docker images"
        id: build-matrix
        shell: bash
        run: |
          hits=""
          for file in $(find . -type f -name "Dockerfile" -exec dirname {} \; | sort -u); do
            hits+="'$file', "
          done
          hits="[${hits%, }]"
          echo "$hits"
          echo "available_images=$hits" >> "$GITHUB_OUTPUT"

  build-and-push:
    needs: [image-tags, build-matrix]
    if: ${{ needs.build-matrix.outputs.available_images != '[]' }}
    uses: maandr/github-actions/.github/workflows/cd-ghcr.yaml@v3
    strategy:
      fail-fast: false
      matrix:
        image_dir: ${{ fromJson(needs.build-matrix.outputs.available_images) }}
    with:
      tags: ${{ needs.image-tags.outputs.tags }}
      labels: ${{ needs.image-tags.outputs.labels }}
      file: ./${{ matrix.image_dir }}/Dockerfile
      context: ./${{ matrix.image_dir }}
    secrets:
      GHCR_PAT: ${{ secrets.CONTAINER_REGISTRY_PAT }}
